server:
  port: 3344

spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/XFang791/microservicecloud-config  #GitHub上面的git仓库名字